// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Base(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/base.templ`, Line: 8, Col: 21}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link rel=\"icon\" type=\"image/x-icon\" href=\"/Static/Pics/icon.png\"><link rel=\"stylesheet\" href=\"/Static/CSS/styles.css\"></head><body class=\"h-screen max-w-screen flex flex-col items-center bg-[url(&#39;/Static/Pics/apple-trees.jpeg&#39;)] bg-fixed bg-cover bg-center font-[Quicksand-Regular]\"><script src=\"/Static/JS/collapsible.js\"></script><nav class=\"w-full max-w-7xl bg-gray-100 flex justify-center items-center gap-8 p-1 mt-2 rounded-3xl backdrop-blur-xs inset-shadow-clay-gray\"><a class=\"text-green-950 text-lg px-2 py-1 cursor-pointer\" href=\"/\">Słownik Upraw</a> <a class=\"text-green-950 text-lg px-2 py-1 cursor-pointer\" href=\"/\">PKWiU</a> <a class=\"text-green-950 text-lg px-2 py-1 cursor-pointer\" href=\"/\">CN</a> <a class=\"text-green-950 text-lg px-2 py-1 cursor-pointer\" href=\"/jak-to-dziala\">Jak To Działa</a> <a class=\"text-green-950 text-lg px-2 py-1 cursor-pointer\" href=\"/api\">API</a></nav><main class=\"max-w-7xl w-full grow p-5 my-4 bg-quinary-400 rounded-3xl backdrop-blur-xs inset-shadow-clay-green\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main><footer class=\"w-full p-2 mb-2 max-w-7xl text-center bg-tertiary-400 rounded-3xl backdrop-blur-xs text-s inset-shadow-clay-brown-regular\">Powered by IERiGŻ. All rights reserved. </footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
